### ISSUE TITLE
Guide outdated temporarily: use steam_chrome branch

### ISSUE THREAD

**Issue by asdfghjkl403622** [Raezroth/Linux-ARM-Gaming-Chroot#16]
hey! thank you so much for the guide! I tried my best to follow it, but I ended up with some kind of issue? I'm on the ppp.

first, the steam updater thingy appears. then when it goes away nothing happens and these messages are spammed over and over again in the console:

steamwebhelper.sh[430]: Runtime for steamwebhelper: defaulting to /home/user1/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[430]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[430]: CEF sandbox already disabled

Did I do something wrong?

**Comment by asdfghjkl403622** [comment]
you need to use the new branch of box64 for the time being. now all that's left is to figure out how to compile it since the chroot is using a 32bits build enviroment

**Comment by Raezroth** [comment]
Updated. Please read the section for manual compiling for box86/64
