### ISSUE TITLE
links broken

### ISSUE THREAD

**Issue by JonathanTippy** [Raezroth/Linux-ARM-Gaming-Chroot#18]
the link that leads back to the install box64/ box86 section from the install steam section is missing ".md" and therefore is a 404
instead of "https://github.com/Raezroth/Linux-ARM-Gaming-Chroot/blob/master/Docs/install-box86_64" it should be "https://github.com/Raezroth/Linux-ARM-Gaming-Chroot/blob/master/Docs/install-box86_64.md"

**Comment by Raezroth** [comment]
Fixed, Thanks for catching it
