### ISSUE TITLE
Why not directly using lxc?

### ISSUE THREAD

**Issue by linsyking** [Raezroth/Linux-ARM-Gaming-Chroot#26]
Lxc could provide great container management.

**Comment by CalcProgrammer1** [comment]
I would suggest Distrobox instead, though I'm not very familiar with LXC.  I just wrote a guide for setting up FEX Emulator in Distrobox over on the postmarketOS wiki:

https://wiki.postmarketos.org/wiki/Steam

Distrobox is a good container solution for this as it manages forwarding X11, Wayland, audio, etc. capability into the container for you, maps your host system home directory into the container, and is persistent.  It can optionally run an init system inside as well.

I also managed to set up box86/box64 in a Debian Distrobox container and am working on a script to do the setup on top of a fresh debian:latest container.

**Comment by linsyking** [comment]
> I would suggest Distrobox instead, though I'm not very familiar with LXC. I just wrote a guide for setting up FEX Emulator in Distrobox over on the postmarketOS wiki:
> 
> https://wiki.postmarketos.org/wiki/Steam
> 
> Distrobox is a good container solution for this as it manages forwarding X11, Wayland, audio, etc. capability into the container for you, maps your host system home directory into the container, and is persistent. It can optionally run an init system inside as well.
> 
> I also managed to set up box86/box64 in a Debian Distrobox container and am working on a script to do the setup on top of a fresh debian:latest container.

Thanks. I am using lxc and it also works great. I had a repo for creating it: https://github.com/linsyking/game-lxc-arm64
