### ISSUE TITLE
deboostrap?

### ISSUE THREAD

**Issue by JonathanTippy** [Raezroth/Linux-ARM-Gaming-Chroot#4]
Linux-ARM-Gaming-Chroot/blob/master/Docs/create-chroot.md 
In the debian based dependancy installer one-liner is included "deboostrap" instead of debootstrap. This results in the error:
E: Unable to locate package deboostrap

**Comment by Raezroth** [comment]
This was a typo that has long been fixed.

**Comment by Raezroth** [comment]
Lol, I guess I fixed it for te arch based line not the debian based my b
